### PR TITLE
Fix compilation with exceptions disabled on MSVC and remove use of alloca

### PR DESCRIPTION
**Pull request by AlpyneDreams**
When compiling NVRHI with exceptions disabled (not necessarily supported, but not uncommon in game engines), the use of `alloca` in `d3d12-raytracing.cpp` causes a compilation errors on MSVC because `alloca` is defined in `<malloc.h>` which is included by `<exception>` (which is included by `<string>`) only when `_HAS_EXCEPTIONS` is not 0.

Instead of just including `<malloc.h>` which is compiler and OS-specific I decided to just replace the usage of `alloca` with a preallocated vector since it is generally considered bad practice to use `alloca` and it's only used in this one specific place in NVRHI.

### CODE REVIEW

**Comment by AlpyneDreams** [comment]
I have read the CLA Document and I hereby sign the CLA
